# Generated by Django 3.0.7 on 2021-05-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerequest',
            name='infer_time',
            field=models.IntegerField(default=0),
        ),
    ]
